name: Release Enhanced Shutter Card

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      BASE: enhanced-shutter-card

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Build project
        run: |
          if [ -f package.json ]; then npm run build; fi

      - name: Inject version into JS
        run: |
          VERSION=${{ steps.version.outputs.version }}

          FILE="dist/${BASE}.js"

          echo "" >> "$FILE"
          echo "window.enhanced_shutter_card_version = \"$VERSION\";" >> "$FILE"

      - name: Rename to HACS stable filename
        run: |
          cp dist/${BASE}.js dist/enhanced-shutter-card.js

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/enhanced-shutter-card.js
            hacs.json
